MAX_STEPS = 20

MISSING_LITERAL = "MISSING – CLINICIAN REVIEW REQUIRED"
CONFLICT_LITERAL = "CONFLICT DETECTED – CLINICIAN REVIEW REQUIRED"
PENDING_LITERAL = "PENDING"
DRAFT_BANNER = "DRAFT FOR CLINICIAN REVIEW — NOT A FINAL CLINICAL DOCUMENT"
